doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        dbname: symfony
        host: db
        port: 3306
        user: root
        password: root
        driver: pdo_mysql
        server_version: 8.0.22
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            VendorMachine:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/VendorMachine/Infrastructure/Configuration/Mappings'
                prefix: 'App\VendorMachine\Domain\Entity'
                alias: VendorMachine
