index:
    path: /
    controller: App\VendorMachine\Infrastructure\Controller\VendorMachineController::index
insert_coin:
    path: /coin/insert
    controller: App\VendorMachine\Infrastructure\Controller\VendorMachineController::insertCoin
    methods: POST
return_coins:
    path: /coin/return
    controller: App\VendorMachine\Infrastructure\Controller\VendorMachineController::returnCoins
purchase_product:
    path: /product/purchase
    controller: App\VendorMachine\Infrastructure\Controller\VendorMachineController::purchaseProduct